server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/java_learning?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
com:
   david:
    name: david
