server:
  port: 8081
spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/java_learning
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/java_learning2
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    elasticsearch:
      cluster-name: lion
      cluster-nodes: 127.0.0.1:9300
com:
   david:
    name: david
